default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: amazon_books_development

test:
  <<: *default
  database: amazon_books_test

production:
  <<: *default
  database: amazon_books_production
  username: amazon_books
  password: <%= ENV['AMAZON_BOOKS_DATABASE_PASSWORD'] %>
